### ISSUE TITLE
Mobile view compatibility 

### ISSUE THREAD

**Issue by binarygeek119** [faush01/ChapterApi#1]
I like to do stuff on emby from phone. But can't with this plugin, because the page doesn't move/scroll. And in some pages doesn't fit on to screen.

I know your busy with other features, but would be a big thing for me.

**Comment by faush01** [comment]
I have also seen this on my phone.
Try this, when you are on the chapter page hit the 3 bars to bring up the main Embry menu then click off the menu to hide the menu again, I can then scroll correctly.

**Comment by binarygeek119** [comment]
that did it. thanks! but i do have to hold phone sideways to see the full page. no big deal.
