### ISSUE TITLE
cant download fingerprint

### ISSUE THREAD

**Issue by binarygeek119** [faush01/ChapterApi#2]
![image](https://user-images.githubusercontent.com/72405030/186841142-ce2f4673-08f0-4c7c-a25e-d987aa896ebd.png)
 
i have 100% intros but cant download them to submit to themeservice. the skip does work just cant download to submit.

**Comment by faush01** [comment]
If you mouse over the last column do you see any cursor change?
Are you using the latest version 1.2.0.5

**Comment by binarygeek119** [comment]
yes am on 1.2.0.5. and no cursor change.
[embyserver.txt](https://github.com/faush01/ChapterApi/files/9431883/embyserver.txt)

**Comment by faush01** [comment]
The only thing I can think of is the icons are not visible for some reason. It is using the standard text font icons that is used in all of emby. If you know how to use the browser debugger (hit f-12) and see if you can identify if there are actual icons there or not.

**Comment by binarygeek119** [comment]
![image](https://user-images.githubusercontent.com/72405030/186892372-522c1041-7e52-4dff-a6a0-0b6d43fbc09a.png)

**Comment by binarygeek119** [comment]
this is from 3rd rock from the sun
![image](https://user-images.githubusercontent.com/72405030/186894041-ff4e9d19-af8d-4239-a84d-b270e195424a.png)

**Comment by faush01** [comment]
well the links are there so it is what I thought, for some reason the icons are not displaying.
If you position the mouse and click the links should still work.
I need to work out why the icons are not showing. 
What browser are your using?
What theme are you using?

**Comment by binarygeek119** [comment]
the links dont show up for 2 broke girls but does for 3rd rock from the sun.
chrome
theme: dark
settings theme: dark

**Comment by faush01** [comment]
oh, it could be the length, they look short < 10 sec

**Comment by binarygeek119** [comment]
ya 2 broke girls intro is quick intro skip does pick it up though.

**Comment by faush01** [comment]
yeah, 10 seconds is to short

if (intro_duration > 10 && intro_duration < 300)

It can detect it but I drop it as a 10 second intro is hardly worth it.
Are 10 second intros common?

**Comment by binarygeek119** [comment]
in that show yes there all the same for the whole show

**Comment by faush01** [comment]
is 10 second intros worth it? its 10 seconds, it is smaller than most skip actions in players and by the time you reach for the remote to select the skip intro the intro is finished.
