### ISSUE TITLE
share show intros from plugin to themeservice

### ISSUE THREAD

**Issue by binarygeek119** [faush01/ChapterApi#3]
be nice to have a check box to auto upload to themeservice.
it would go thought all checked boxes to fingerprint and then bulk upload them to themeservice for review.

**Comment by faush01** [comment]
You dont need to upload ALL the episode intros, you only need one per series or some times one per season. All the intros should be the same and the idea is you should only need one of them to then be able to detect all the intros for the whole series.

Some tv shows have different intros per season and in this case you may need one intro defined per season.
